### ISSUE TITLE
Map::toArray() and classes

### ISSUE THREAD

**Issue by Frago9876543210** [php-ds/ext-ds#131]
```php
<?php
class A{}

$map = new \Ds\Map();

$map->put(new A, 0);
$map->put(new A, 1);

var_dump($map->toArray());
```

```
Warning: Illegal offset type in bug.php on line 9
Warning: Illegal offset type in bug.php on line 9
array(0) {
}
```

I think it should return array with `spl_object_hash($class) => value`

**Comment by rtheunissen** [comment]
This is expected behaviour.

`toArray` will attempt to create an associative array with the same keys as the map. It is not possible to use the hash value, because the hash and the key are not equal. For example, if three objects have the same hash but are not equal, all three should be in the map.

If you use objects as keys, `toArray` will fail.
